### PR TITLE
All tests are passing

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by itcharlie** [comment]
Thanks for the help. Hope to contribute some more now.

**Comment by yanick** [comment]
And now that all tests are passing, don't forget to do a Pull Request to the main repository so that it's merged in the official distro! :-)

**Comment by itcharlie** [comment]
Hi Yanick,

One thing I noticed is that I still need Moose ( example below )  in order
for the tests to pass. I been doing some reading on Moo and learned that
Moo classes can "autoinflate" into Moose classes when needed ( I have been
struggling trying to figure out when this actually happens - I only know of
that one case when **PACKAGE**->meta->make_immutable; is called. ) .

cgonzalez@cgonzalez-X220:~/projects/p5-Text-Xslate$ watcher --dir lib/ --
perl -I lib/  t/020_interface/014_customize_option.t
[2015-05-22T20:05:14] watching: lib/
[2015-05-22T20:05:14] Forked process: perl -I lib/
t/020_interface/014_customize_option.t
ok 1 - detect unknown option
ok 2 - no unknown option error
Can't locate Moose.pm in @INC (you may need to install the Moose module)
(@INC contains: lib/
/home/cgonzalez/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2/x86_64-linux
/home/cgonzalez/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2
/home/cgonzalez/.plenv/versions/5.20.2/lib/perl5/5.20.2/x86_64-linux
/home/cgonzalez/.plenv/versions/5.20.2/lib/perl5/5.20.2 .) at
/home/cgonzalez/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2/Moo/HandleMoose.pm
line 58.

# Tests were run but no plan was declared and done_testing() was not seen.

# Looks like your test exited with 2 just after 2.

^C[2015-05-22T20:05:17] SIGINT received
[2015-05-22T20:05:17] Terminate process: 10529

Tests do pass when I load a directory with Moose Package ( ext_lib/perl5/ )

cgonzalez@cgonzalez-X220:~/projects/p5-Text-Xslate$ watcher --dir lib/ --
perl -I lib/ -I ../ext_lib/lib/perl5/
t/020_interface/014_customize_option.t
[2015-05-22T20:05:05] watching: lib/
[2015-05-22T20:05:05] Forked process: perl -I lib/ -I ../ext_lib/lib/perl5/
t/020_interface/014_customize_option.t
ok 1 - detect unknown option
ok 2 - no unknown option error
ok 3 - my_compiler_option
ok 4 - my_parser_option
ok 5 - load_file -> success
1..5

 Should I still move forward with the pull request knowing this?

Best,

Charlie

Charlie Gonzalez
(E) itcharlie@gmail.com
https://github.com/itcharlie

**Comment by itcharlie** [comment]
Been thinking about this and it makes more sense to have a pull request to the main repository. If anything we are 3/4 into making it fully Moo instead of Moose. Going to create pull request now. Thanks Yanick.

**Comment by itcharlie** [comment]
Sorry didn't know what I was dealing with until I read the original issue again. I forgot this was a Mouse to Moo conversion rather than a Moose to Moo. Thanks again for your help Yanick.

**Comment by yanick** [comment]
Heh. I must say, it's sometimes  hard to keep track of all those Mo\* modules. :-)

As for the autoinflating part, it touches the big difference between Moose and Moo, which is Moose meta-layer that makes  full introspection possible. For the sake of performance, Moo does away with that. Which is not too foolish, as in most cases you don't need that introspection. But in the cases where you /do/ need it (which is when you access $foo->meta), Moo is intended to be smart enough to automatically change the object such that it's based on Moose rather than Moo. 

Fortunately, as you already realized, this is higher magic that we won't need here. :-)

**Pull request merged**
